server:
  port: 8080

spring:
  application:
    name: CHIT-FUND
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chitfund
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 600000
      connection-timeout: 300000
      pool-name: SpringBootHikariCP
      connection-init-sql: select 1 from dual
      connection-test-query: select 2 from dual
  jpa:
    database: MYSQL
    hibernate.ddl-auto: true
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jpa.show-sql: true
  jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  
  jackson:
    default-property-inclusion: non-null

security:
  jwt:
    enable: true
    secret: mySecret
    expiration: 86400000
