package com.chitfund.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Collection generated by hbm2java
 */
@Entity
@Table(name = "collection")
public class Collection implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaID")
	private Area area;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loanID", nullable = false)
	private Loan loan;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	private Users users;
	
	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	private long amount;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "CollectDate", nullable = false, length = 10)
	private Date collectDate;

	public Collection() {
	}

	public Collection(Loan loan, Users users, long amount, Date collectDate) {
		this.loan = loan;
		this.users = users;
		this.amount = amount;
		this.collectDate = collectDate;
	}

	public Collection(Area area, Loan loan, Users users, long amount, Date collectDate) {
		this.area = area;
		this.loan = loan;
		this.users = users;
		this.amount = amount;
		this.collectDate = collectDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@JsonIgnore
	public Loan getLoan() {
		return this.loan;
	}

	public void setLoan(Loan loan) {
		this.loan = loan;
	}

	@JsonIgnore
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public Date getCollectDate() {
		return this.collectDate;
	}

	public void setCollectDate(Date collectDate) {
		this.collectDate = collectDate;
	}

}
