package com.chitfund.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Users implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@Column(name = "name", nullable = false, length = 45)
	private String name;
	
	@Column(name = "username", unique = true, nullable = false, length = 45)
	private String username;

	@Column(name = "password", length = 32)
	private String password;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaID")
	private Area area;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<UserRoles> userRoles = new HashSet<UserRoles>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Ledger> ledgers = new HashSet<Ledger>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Collection> collections = new HashSet<Collection>(0);

	public Users() {
	}

	public Users(String name) {
		this.username = name;
	}

	public Users( String name, String username, String password, Area area, Set<UserRoles> userRoles, Set<Ledger> ledgers,
			Set<Collection> collections) {
		this.name = name;
		this.username = username;
		this.password = password;
		this.area = area;
		this.userRoles = userRoles;
		this.ledgers = ledgers;
		this.collections = collections;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@JsonIgnore
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	@JsonIgnore
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}
	
	@JsonIgnore
	public Set<UserRoles> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(Set<UserRoles> userRoles) {
		this.userRoles = userRoles;
	}

	@JsonIgnore
	public Set<Ledger> getLedgers() {
		return this.ledgers;
	}

	public void setLedgers(Set<Ledger> ledgers) {
		this.ledgers = ledgers;
	}

	@JsonIgnore
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
