package com.logan.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Area implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	
	@Column(name = "name", unique = true, nullable = false, length = 45)
	private String name;
	
	@Column(name = "details", length = 65535)
	private String details;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	private Set<Collection> collections = new HashSet<Collection>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	private Set<Customer> customers = new HashSet<Customer>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	private Set<Loan> loans = new HashSet<Loan>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	private Set<Ledger> ledgers = new HashSet<Ledger>(0);
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	private Set<Users> userses = new HashSet<Users>(0);

	public Area() {
	}

	public Area(String name) {
		this.name = name;
	}

	public Area(String name, String details, Set<Collection> collections, Set<Customer> customers, Set<Loan> loans,
			Set<Ledger> ledgers, Set<Users> userses) {
		this.name = name;
		this.details = details;
		this.collections = collections;
		this.customers = customers;
		this.loans = loans;
		this.ledgers = ledgers;
		this.userses = userses;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@JsonIgnore
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

	@JsonIgnore
	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

	@JsonIgnore
	public Set<Loan> getLoans() {
		return this.loans;
	}

	public void setLoans(Set<Loan> loans) {
		this.loans = loans;
	}

	@JsonIgnore
	public Set<Ledger> getLedgers() {
		return this.ledgers;
	}

	public void setLedgers(Set<Ledger> ledgers) {
		this.ledgers = ledgers;
	}

	@JsonIgnore
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
