package com.logan.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Ledger generated by hbm2java
 */
@Entity
@Table(name = "ledger")
public class Ledger implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaID", nullable = false)
	private Area area;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loanID")
	private Loan loan;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID")
	private Users users;

	@Temporal(TemporalType.DATE)
	@Column(name = "EntryDate", nullable = false, length = 10)
	private Date entryDate;

	@Column(name = "entryType", nullable = false)
	private String entryType;

	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	private long amount;

	@Column(name = "creOrDe", nullable = false)
	private String creOrDe;

	public Ledger() {
	}

	public Ledger(Area area, Date entryDate, String entryType, long amount, String creOrDe) {
		this.area = area;
		this.entryDate = entryDate;
		this.entryType = entryType;
		this.amount = amount;
		this.creOrDe = creOrDe;
	}

	public Ledger(Area area, Loan loan, Users users, Date entryDate, String entryType, long amount, String creOrDe) {
		this.area = area;
		this.loan = loan;
		this.users = users;
		this.entryDate = entryDate;
		this.entryType = entryType;
		this.amount = amount;
		this.creOrDe = creOrDe;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@JsonIgnore
	public Loan getLoan() {
		return this.loan;
	}

	public void setLoan(Loan loan) {
		this.loan = loan;
	}

	@JsonIgnore
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getEntryDate() {
		return this.entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public String getEntryType() {
		return this.entryType;
	}

	public void setEntryType(String entryType) {
		this.entryType = entryType;
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public String getCreOrDe() {
		return this.creOrDe;
	}

	public void setCreOrDe(String creOrDe) {
		this.creOrDe = creOrDe;
	}

}
