package com.logan.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Loan generated by hbm2java
 */
@Entity
@Table(name = "loan")
public class Loan implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaID", nullable = false)
	private Area area;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customerID", nullable = false)
	private Customer customer;

	@Column(name = "amount", nullable = false, precision = 10, scale = 0)
	private long amount;

	@Temporal(TemporalType.DATE)
	@Column(name = "startDate", length = 10)
	private Date startDate;

	@Column(name = "dueAmount", precision = 10, scale = 0)
	private Long dueAmount;

	@Column(name = "loanType")
	private String loanType;

	@Column(name = "status")
	private String status;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loan")
	private Set<Ledger> ledgers = new HashSet<Ledger>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loan")
	private Set<Collection> collections = new HashSet<Collection>(0);

	public Loan() {
	}

	public Loan(Area area, Customer customer, long amount) {
		this.area = area;
		this.customer = customer;
		this.amount = amount;
	}

	public Loan(Area area, Customer customer, long amount, Date startDate, Long dueAmount, String loanType,
			String status, Set<Ledger> ledgers, Set<Collection> collections) {
		this.area = area;
		this.customer = customer;
		this.amount = amount;
		this.startDate = startDate;
		this.dueAmount = dueAmount;
		this.loanType = loanType;
		this.status = status;
		this.ledgers = ledgers;
		this.collections = collections;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@JsonIgnore
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@JsonIgnore
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Long getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(Long dueAmount) {
		this.dueAmount = dueAmount;
	}

	public String getLoanType() {
		return this.loanType;
	}

	public void setLoanType(String loanType) {
		this.loanType = loanType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@JsonIgnore
	public Set<Ledger> getLedgers() {
		return this.ledgers;
	}

	public void setLedgers(Set<Ledger> ledgers) {
		this.ledgers = ledgers;
	}

	@JsonIgnore
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
