package com.logan.domain;
// Generated 17 May, 2018 4:01:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Users implements java.io.Serializable {

	@Id
	@Column(name = "loginID", unique = true, nullable = false)
	private int loginId;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "areaID")
	private Area area;

	@Column(name = "name", unique = true, nullable = false, length = 45)
	private String name;

	@Column(name = "password", length = 32)
	private String password;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Ledger> ledgers = new HashSet<Ledger>(0);

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	private Set<Collection> collections = new HashSet<Collection>(0);

	public Users() {
	}

	public Users(int loginId, String name) {
		this.loginId = loginId;
		this.name = name;
	}

	public Users(int loginId, Area area, String name, String password, Set<Ledger> ledgers,
			Set<Collection> collections) {
		this.loginId = loginId;
		this.area = area;
		this.name = name;
		this.password = password;
		this.ledgers = ledgers;
		this.collections = collections;
	}

	public int getLoginId() {
		return this.loginId;
	}

	public void setLoginId(int loginId) {
		this.loginId = loginId;
	}

	@JsonIgnore
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@JsonIgnore
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@JsonIgnore
	public Set<Ledger> getLedgers() {
		return this.ledgers;
	}

	public void setLedgers(Set<Ledger> ledgers) {
		this.ledgers = ledgers;
	}

	@JsonIgnore
	public Set<Collection> getCollections() {
		return this.collections;
	}

	public void setCollections(Set<Collection> collections) {
		this.collections = collections;
	}

}
